#!/usr/bin/python
import os, json

assets = []
for fname in os.listdir('.'):
    if fname in (
        'empty.png', 'package-header.jpg', 'package.png',
        'screenshot.jpg', 'screenshot-1.jpg', 'blank.png'
    ):
        continue
    if fname.endswith('.jpg') or fname.endswith('.png'):
        assets.append((fname, "image", 5))
    if fname.endswith('.mp4'):
        assets.append((fname, "video", 5))

assets.sort()

with file('config.json', 'wb') as f:
    f.write(json.dumps(dict(
        playlist = [dict(
            duration = duration,
            file = dict(
                asset_name = fname,
                type = type,
            )
        ) for fname, type, duration in assets],
        switch_time = 0,
        kenburns = False,
        synced = False,
        rotation = 0,
        audio = True,
    )))

print("config.json created (%d assets). start info-beamer now" % len(assets))
