#!/usr/bin/python
import time, socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
while 1:
    now = "%.6f" % time.time() 
    sock.sendto('root/clock/set:%s' % now, ('127.0.0.1', 4444))
    time.sleep(1)
